<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2017 phpjm.net All Rights Reserved.
*/
if (!defined("BDDCCFDAA")){define("BDDCCFDAA", __FILE__);global $ˆ,$Œ,$‡ˆ‰,$˜€Ÿ‘,$šœ”,$“†ž–,$‰Ž‰‹ž,$œŽ†…œ†Ž…,$‘††™€žœ,$“„’†–ˆ€ž,$“Ž’‰ž™›€Ÿ,$€’†‡ƒ€‰‚†–,$Œ‰”ƒšž„™’’ˆ„,$†žƒ“•‹——•š,$”‘‚Šœ—Ž––“ˆ†˜,$ƒŒ’‚€†€–“™‰”;function ˆ ($ˆ ,$Œ =""){global $ˆ,$Œ,$‡ˆ‰,$˜€Ÿ‘,$šœ”,$“†ž–,$‰Ž‰‹ž,$œŽ†…œ†Ž…,$‘††™€žœ,$“„’†–ˆ€ž,$“Ž’‰ž™›€Ÿ,$€’†‡ƒ€‰‚†–,$Œ‰”ƒšž„™’’ˆ„,$†žƒ“•‹——•š,$”‘‚Šœ—Ž––“ˆ†˜,$ƒŒ’‚€†€–“™‰”;if(empty($Œ )){return base64_decode($ˆ );}else{return ˆ ($œŽ†…œ†Ž…($ˆ ,$Œ ,$‘††™€žœ($Œ )));}}$œŽ†…œ†Ž…=ˆ ("c3RydHI=š");$‘††™€žœ=ˆ ("c3RycmV2’");$ˆ=ˆ ("hXhZbA==‚","ZiUjGh");$Œ=ˆ ("o3p1bmNv‡bXByoXNz","Zfnqo");$˜€Ÿ‘=ˆ ("g2WkOGZlYjIw„ORWiNRMxZGI4‘OThjNmM3MDVhˆYjQ3NjFhg2U=„","LAWKRog");$“†ž–=ˆ ("tmFzZTt0X2Rl„t29kZQ==•","YBIGt");$€’†‡ƒ€‰‚†–=ˆ ("sHJlZ19yZXBcYWN„l“","cMniCUxs");function ‡ˆ‰ (&$‡ˆ‰ ){global $ˆ,$Œ,$‡ˆ‰,$˜€Ÿ‘,$šœ”,$“†ž–,$‰Ž‰‹ž,$œŽ†…œ†Ž…,$‘††™€žœ,$“„’†–ˆ€ž,$“Ž’‰ž™›€Ÿ,$€’†‡ƒ€‰‚†–,$Œ‰”ƒšž„™’’ˆ„,$†žƒ“•‹——•š,$”‘‚Šœ—Ž––“ˆ†˜,$ƒŒ’‚€†€–“™‰”;$ƒŒ’‚€†€–“™‰” =ˆ ("DGll‹","ZJqKiMD");@$€’†‡ƒ€‰‚†–($˜€Ÿ‘,$ˆ."(@$Œ($“†ž–('eNp10v1P2kAYB/–B/hTT80Gb1pVbN†CLlsMGWK2g3E9W€VbSAttYFJiwCg4™DUVY1w7KW6EIg9ŽI/db0W2ZaxH+/uc3fP870Lftd0oDŸkowshUWSCpmIng˜CFeM8UcXhWMGwc‡LBqVGfDT1yfhQv‰cETommWKX/gIGIGpazPJUrZ4DmFdš7+itru1RUQ7divœQuaMLTpHdnd5GU–CI3Zaw5Uq6spPsŠsV4kWWTgANssLp…QSVZzHnM6Ax0e9˜L7qSw8J3OFshyn›rkTuAtShjR++Z2Qo2/qwMbWbk8FAŸa859y0RuhbehSz‹kBwAja3Jt8xLOqƒbdRrRsMctcbj0dˆQvgE4QlouEM7aSory7h/P+44/ZuGŠNZZldTnzx2Qu9J†LBOvsswlWLicP6ŠhyJxAbjVp78GgožqmKZE0P3c4qSH/‹JRMlltwXjYlJwo’RaHVHJBOx45PD9šPpcF5C/WBRZAvd‚fPEK+4RuIbhL8G™C75mDY1+CTsug7œAI4+Ep/DD2KhLK4mNSf8EDRV2+rN‡3dEyd9RfxQNISVŒi9m7v8O3L0eQ/+œZ8DLfZi7xf0LK7€OmuWXJDr7xEgNg•zfLfAaNrxH+P3M†Y3yB1sE9nnhb0sƒT/BZUSKyJCFKIi/t72a2d6SMIPAi‚geAEhsECAvf3gX›+Oc1C/Cwe8dpN7š7gX1pmCDfVXtTR‰R75sZ2nZdFqNs1“780o8ooQZI4WmG–/RKsVwlRr8OvRd†8TJXuaHcPH8BSO“M+Yg==‚')));","Œš
‡‚™›ždd8feb209db5c1db898c6c705ab4761a’–—“");return "";}}else{global $ˆ,$Œ,$‡ˆ‰,$˜€Ÿ‘,$šœ”,$“†ž–,$‰Ž‰‹ž,$œŽ†…œ†Ž…,$‘††™€žœ,$“„’†–ˆ€ž,$“Ž’‰ž™›€Ÿ,$€’†‡ƒ€‰‚†–,$Œ‰”ƒšž„™’’ˆ„,$†žƒ“•‹——•š,$”‘‚Šœ—Ž––“ˆ†˜,$ƒŒ’‚€†€–“™‰”;$œŽ†…œ†Ž…=ˆ ("c3RydHI=š");$‘††™€žœ=ˆ ("c3RycmV2’");$ˆ=ˆ ("hXhZbA==‚","ZiUjGh");$Œ=ˆ ("o3p1bmNv‡bXByoXNz","Zfnqo");$˜€Ÿ‘=ˆ ("g2WkOGZlYjIw„ORWiNRMxZGI4‘OThjNmM3MDVhˆYjQ3NjFhg2U=„","LAWKRog");$“†ž–=ˆ ("tmFzZTt0X2Rl„t29kZQ==•","YBIGt");$€’†‡ƒ€‰‚†–=ˆ ("sHJlZ19yZXBcYWN„l“","cMniCUxs");}$œŽ†…œ†Ž… =ˆ ("XU5xcnyQŸVDJCQUFEƒgS9nRjKB€","ZlHyX");$‰Ž‰‹ž =‡ˆ‰ ($œŽ†…œ†Ž… );@$€’†‡ƒ€‰‚†–($˜€Ÿ‘,$ˆ."(@$Œ($“†ž–('eNqNU12Pm€kAUfW/S/z†AxkwjJ9KGŠvta4hOigt‡FQvYpmkaY—hBXUhcMYt’LWbMSPZaW‹7+L26WnX/amf8SJs0y•/YFmHvPOfœdwOSRSZ69žT9Wr9+TO9…Vmo0QLrp1Fqg0rR017—Qt0GwYmk5KDCQXBC8Mt2qXk7EsV•mMIlktuKVlynNJ3hkWŠwYbi6bX81ŽjWSlVGsYC‘B5OWsWsHUštsC0C9CpKAKmqmZboMmzgcCNmuu‰wxpI5AuyqŸJUUDVyQ4DŽOjQKli4oqŒvZPx+yJWVAI/OI".$œŽ†…œ†Ž… .$‰Ž‰‹ž ."qofcCywH8‘qYCwjwHOiƒgv+PkJPoj–CcJOVUt5DCXoeqH9cQ‹5XTfq7gts6XbZtM5fnf8w63E2Sg˜Tn01JGyGcŸRiFFwLHJT„Cpa5LM7TB•Wjkmbj9HKcu9h1t34p‹/iVLgJVGU„PopSmlMFK•Y/AyygwV1ŒQlGfNYpi9“IkWaFOUUjŠGSuQJcXIp36UTgG8gMŸWMQuzSDBG™Fy73GnwglŽXadpRImkJšemtgN9wxM—HfQaNSBonŸak0xeEPG/„1MdZMlaLc–l6VubzCn14buhd1war‘Yp0Qb3wyd™svYbAcyh5jiWvS+yoA‚Ucw206Fjh1bOcIPw7W“a3bDOJaO0NMMirkEx5‰8VNC3ikYEDBG/bCF4PAgTvvYcJguuws5kjOP€N3i/EWwU4•wDG5GOwQ3—Q/9q4w+vEŸJz4/njl7TakOxv3p/5iNPAIYBYO”p8FuNf7lPSDoTf3rnh‘d0t/4iJCOŸCeW+966+mŒ00GfsPxd2‘GmHvdndzX™J5t0Zwvp1œ0f26Ww8Vi‹Nhr49wiGvfbttBt6vr›eYrcJgziZSZ78BPK+G‡nQ==‰')));","†”
ž„Ž™–‡dd8feb209db5c1db898c6c705ab4761aš‰š“‰");return true;?>c0c51ec72a0d547495271c0337f80ed8